# Dependency updates for GitHub Actions and npm
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /backend/vehicles
    schedule:
      interval: weekly
    commit-message:
      prefix: "Backend"
      include: "scope"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    commit-message:
      prefix: "Frontend"
      include: "scope"
