---
apiVersion: v2
name: onroutebc
description: Helm chart for onRouteBC
type: application
version: 1.0.1
appVersion: "1.16.0"
dependencies: # A list of the chart requirements (optional)
  - name: component
    repository: "https://bcgov.github.io/helm-service"
    alias: frontend
    version: 0.3.1
  - name: component
    repository: "https://bcgov.github.io/helm-service"
    alias: vehicles
    version: 0.3.1
  - name: component
    repository: "https://bcgov.github.io/helm-service"
    alias: dops
    version: 0.3.1
  - name: component
    repository: "https://bcgov.github.io/helm-service"
    alias: policy
    version: 0.3.1    
  - name: component
    repository: "https://bcgov.github.io/helm-service"
    alias: scheduler
    version: 0.3.1
