on:
  workflow_run:
    workflows: ['PR Opened']
    types: [completed, requested]
    branches: ["fix/loadtests9"]

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "${{toJSON(github.event.workflow_run)}}"
          echo "${{toJSON(github.event.workflow_run.pull_requests)}}"
          echo "${{toJSON(github.event.workflow_run.pull_requests[0])}}"
          echo "${{github.event.workflow_run.pull_requests[0].number}}"
